### ISSUE TITLE
Move content of Project_Outline.doc to README.md

### ISSUE THREAD

**Issue by abadi199** [MrSeanGorman/liftoff-assignments#1]
@MrSeanGorman 
It's preferable to use markdown (see https://guides.github.com/features/mastering-markdown) when writing documentation on GitHub because people will be able to see the content of the document directly from GitHub without downloading the file and installing additional application to read it. 

I recommend moving the content from `Project_Outline.doc` into `README.md`. Let me know if you need any help in writing markdown.

**Comment by MrSeanGorman** [comment]
@abadi199 
I moved the content over and resubmitted the canvas assignment with the proper link. I also formatted it properly for markdown.

**Comment by abadi199** [comment]
:+1:
